name: Deploy Frontend
on:
  push:
    branches:
      - master  # Change to match your repo's branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true cygnetops/react-test npm test
